---
title: "Figure3"
author: "Johan"
date: "01/02/2024"
output:
  html_document:
    toc: yes
    toc_depth: 3
    toc_float: yes
    code_folding: hide
    df_print: paged
---



```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)

library(Seurat)



library(tidyverse)
library(patchwork)
source("../customFunctions.R")
source("../colorSchemes.R")
source("../loadGeneInfo.R")

select = dplyr::select

summarise = dplyr::summarise

repositoryPath = "~/git/Rising-Lab/MajorGland_paper"

```


## Geneinfo

```{r load geneInfo}

geneInfo = getGeneInfoFull(repositoryPath)

```

## SampleInfo


```{r}



spatial.combined.info = readRDS(file = "~/Box/bridgeSpider/spatialRNA/seurat/spatial.combined.info.RDS.2")
# Filter bad annotation
spatial.combined.info = subset(spatial.combined.info,SilkGlands != "unsure") 
spatial.combined.info = subset(spatial.combined.info,SilkGlands != "ampullate" )

# Add annotation
spatial.combined.info$tissue = "Gland"
spatial.combined.info$tissue[spatial.combined.info$SilkGlands == "OtherTissue"] = "OtherTissue"

spatial.combined.info@meta.data %>% select(SpotID,SilkGlands,x,y,Cluster,SilkGlands2,tissue) -> MD2 

LarSco.spatial.combined = readRDS("~/git/Rising-Lab/MajorGland_paper/data/spatialRNA/raw_8_slides.RDS")
LarSco.spatial.combined$SpotID = rownames(LarSco.spatial.combined@meta.data)

LarSco.spatial.combined = subset(LarSco.spatial.combined,SpotID %in% MD2$SpotID)
LarSco.spatial.combined = addMetaDataToSpatialData(LarSco.spatial.combined,MD2 )


 
# Make sure there is the same number of cells and annotation



```


```{r}


#SilkGlands
DimPlot(spatial.combined.info, 
        reduction = "umap",
        group.by = "SilkGlands",  
        pt.size = 0.05,label = TRUE) + 
  scale_color_manual(values = pal_pastel2)
#ggsave("~/Box/bridgeSpider/paper1/main/figures/figure2/glands_vs_other.dimPlot.color.pdf")

```

# Removing other tissues spots and slides

```{r}
spatial.combined.info.glands = subset(spatial.combined.info,SilkGlands != "OtherTissue") 
subslides = c("Slide1","Slide2","Slide3","Slide4","Slide5","Slide8")
spatial.combined.info.glands = subset(x = spatial.combined.info.glands, Sample %in% subslides)

```
## Figure 3 C

```{r}



spatial.combined.info.glands <- RunPCA(spatial.combined.info.glands,
                                  features = VariableFeatures(object = spatial.combined.info.glands), 
                                  seed.use = 1234)



#ElbowPlot(spatial.combined.info.glands)

####cluster cells
spatial.combined.info.glands <- FindNeighbors(spatial.combined.info.glands, dims = 1:20)
spatial.combined.info.glands <- FindClusters(spatial.combined.info.glands, resolution = 0.5)

###UMAP
spatial.combined.info.glands <- RunUMAP(spatial.combined.info.glands, dims = 1:20, seed.use = 1234)
DimPlot(spatial.combined.info.glands, 
        reduction = "umap",
        group.by = "SilkGlands2",  
        pt.size = 0.3, label = TRUE,order =  c("Minor","Flagelliform","Tubuliform","Major",
                                             "Pyriform","Aciniform","Aggregate","Aggregate duct")) + 
  scale_color_manual(values = pal_pastel2)

ggsave("../../figures/figure3/figure3B.pdf")


```


## Figure 3 A,B
```{r}


LarSco.spatial.combined.glands = subset(LarSco.spatial.combined,
                                        SpotID %in%spatial.combined.info.glands$SpotID  )
subset(LarSco.spatial.combined.glands, Sample == "Slide4") -> LarSco.spatial.combined.glands.slide4
list = LarSco.spatial.combined.glands.slide4@images 
list2 = list[4]
LarSco.spatial.combined.glands.slide4@images = list2
SpatialPlot(LarSco.spatial.combined.glands.slide4,
            group.by =  "SilkGlands2",
            cols = pal_pastel2,
            alpha = 1,
            pt.size.factor = 1.3,
            crop = FALSE) +NoLegend() -> plot.3B



SpatialPlot(LarSco.spatial.combined.glands.slide4,
            group.by =  "SilkGlands2",
            cols = pal_pastel2,
            alpha = 0,
            pt.size.factor = 1.3,
            crop = FALSE) +NoLegend() -> plot.3A

plot.3A+ plot.3B+ plot_layout(ncol = 1)

ggsave("../../figures/figure3AB.pdf")


```





# Visualise expression of spidroin genes.
## Supplementary figure 14
```{r }

LarSco.spatial.combined.glands = subset(LarSco.spatial.combined,SpotID %in% spatial.combined.info.glands$SpotID)


table(LarSco.spatial.combined.glands$SilkGlands2)

g1 = getGeneInfoFull(repositoryPath) %>% filter(Group == "Spidroin")
g1 = g1 %>% arrange(scGeneName) 

LarSco.spatial.combined.glands <- ScaleData(LarSco.spatial.combined.glands, verbose = FALSE)


order  = g1$scGeneName[c(3,1,2,4,5,6,30,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,29,31,27,28,32,33,34,35)]

VlnPlot(LarSco.spatial.combined.glands,features = order,assay = "Spatial",
        group.by ="SilkGlands2")+ theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))

ggsave("../../supplementaryFigures/SuppFig15/SuppFig15.violinPlot.pdf", width = 20, height = 30) 

```




