---
title: "Clustering"
author: "Wenqing Chen"
date: "2023-02-22"
output: html_document

params:
  repositoryPath: ~/git/spidersilk
  geneInfo: Rscripts/loadGeneInfo.R
  extraFunctions: Rscripts/customFunctions.R
  submajormarker: results/scRNA/majorGland/major.glandSpecific.csv
  minorResultDir: results/scRNA/minorGland/integration_add_MarkerGenes
  majorResultDir: results/scRNA/majorGland
  ampullateResultDir: results/scRNA/AmpullateGland
  
  
---

# library
```{r setup2, include=FALSE}

library(Seurat)
library(tidyverse)
library(dplyr) 
library(cowplot)
library(ggplot2)
library(pheatmap)
library(rafalib)
library(ggraph)
library(clustree)
library(ComplexHeatmap)
library(circlize)

source(paste(params$repositoryPath, params$geneInfo, sep = "/"))
source(paste(params$repositoryPath, params$extraFunctions, sep = "/"))
geneInfo = getGeneInfoFull()


#install.packages("wordcloud")
library(wordcloud)
#install.packages("wordcloud2")
library(wordcloud2)




```



# Gene information
```{r}

proteinInfo = getMajorAmpullateGlandProteinsSC()

geneInfo = getGeneInfoFull()


```
```{r}
fimo = read_tsv("../../sequences/spidroin/ampullate/fimo_out/fimo.tsv")


fimo %>% 
  filter(`q-value`< 0.00001)%>%
  group_by(motif_alt_id) %>%
  summarise(n = n())


fimo %>% 
  filter(`q-value`< 0.00001)%>%
  ggplot(aes(fill = motif_alt_id, x = sequence_name)) +
  geom_bar()+
  theme(axis.text.x=element_text(angle = -90, hjust = 0))


fimo %>% group_by(sequence_name) %>%
  arrange(`q-value`) %>%
  slice_head(n = 1000)%>% 
  ggplot(aes(fill = motif_alt_id, x = sequence_name)) +
  geom_bar()+
  theme(axis.text.x=element_text(angle = -90, hjust = 0))


fimo %>%
  arrange(sequence_name,start) %>%
  filter(score > 30) %>%
  filter(`q-value`< 0.000000001)%>% 
  ggplot(aes(fill = motif_alt_id, x = sequence_name)) +
  geom_bar()+
  theme(axis.text.x=element_text(angle = -90, hjust = 0))


```
